logging:
  level:
    root: INFO

# https://github.com/aws/aws-msk-iam-auth
spring:
  kafka:
    consumer:
      max-poll-records: 1
      fetch-max-wait: 300000
      bootstrap-servers:
        - b-1.hopeunexistservicems.asp21y.c2.kafka.ap-northeast-2.amazonaws.com:9098 # I AM endpoint
        - b-2.hopeunexistservicems.asp21y.c2.kafka.ap-northeast-2.amazonaws.com:9098 # I AM endpoint
      auto-offset-reset: latest
      properties:
        "sasl.mechanism": AWS_MSK_IAM
        "sasl.jaas.config": "software.amazon.msk.auth.iam.IAMLoginModule required;"
        "sasl.client.callback.handler.class": "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
      security:
        protocol: SASL_SSL
